version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    name: "${SIMVA_SERVICE_NETWORK:-traefik_services}"
    external: true

services:
  dockhand:
    << : *default-opts
    cpus: "0.5"
    mem_limit: 512m
    mem_reservation: 256m
    pids_limit: 256
    image: ${SIMVA_DOCKHAND_IMAGE:-fnsys/dockhand}:${SIMVA_DOCKHAND_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data
    hostname: ${SIMVA_DOCKHAND_HOST_SUBDOMAIN:-dockhand}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - ${SIMVA_DOCKHAND_HOST_SUBDOMAIN:-dockhand}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - ${SIMVA_DOCKHAND_HOST_SUBDOMAIN:-dockhand}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dockhand.loadbalancer.server.port=3000"
      - "traefik.http.routers.dockhand.rule=Host(`${SIMVA_DOCKHAND_HOST_SUBDOMAIN:-dockhand}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.dockhand.middlewares=dashboardAuth@file"

volumes:
  dockhand_data:
    external: true