version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    name: "${SIMVA_SERVICE_NETWORK:-traefik_services}"
    external: true

services:
  minio-mig:
    << : *default-opts
    image: ${SIMVA_MINIO_IMAGE:-quay.io/minio/minio}:RELEASE.2022-06-25T15-50-16Z
    entrypoint: >
      /bin/sh -c '
        if [ ! -e "/etc/ssl/certs/internal-CA.pem" ]; then
          cp /root/.minio/certs/CAs/rootCA.pem "/etc/ssl/certs/internal-CA.pem";
          cat "/etc/ssl/certs/internal-CA.pem" >> /etc/ssl/cert.pem;
        fi;
        /usr/bin/docker-entrypoint.sh $$@;
      '
    ports:
     - 9000:9000
    command:
     - '--'
     - 'server'
     - '--console-address :9001'
     - '/data'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - minio_mig_data:/data
      - ${SIMVA_TLS_HOME?TLS home folder required}/ca:/root/.minio/certs/CAs
      - ${SIMVA_CONTAINER_TOOLS_HOME:-/home/vagrant/docker-stacks/container-tools}:/container-tools
      - ${SIMVA_BIN_HOME:-/home/vagrant/simva-infra/docker-stacks/bin}/wait-available.sh:/bin/wait-available.sh:ro
    environment:
      MINIO_ROOT_USER: "${SIMVA_MINIO_ACCESS_KEY:-minio}"
      MINIO_BROWSER_REDIRECT_URL: "http://${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}-mig.${SIMVA_INTERNAL_DOMAIN:-internal.test}:9001"
      MINIO_SERVER_URL: "http://${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}-mig.${SIMVA_INTERNAL_DOMAIN:-internal.test}:9000"
      MINIO_ROOT_PASSWORD: "${SIMVA_MINIO_SECRET_KEY:-secret}"
      WAIT_TIMEOUT: ${SIMVA_WAIT_TIMEOUT:-240}
      SIMVA_WAIT_TIME: ${SIMVA_WAIT_TIME:-10}
      SIMVA_MAX_RETRIES: ${SIMVA_MAX_RETRIES:-20}
    restart: on-failure:${SIMVA_MAX_RETRIES:-20}
    healthcheck:
      test: "curl -sS http://localhost:9000/minio/health/live || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
    hostname: ${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}-mig.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - ${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}-mig.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - ${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}-mig.${SIMVA_INTERNAL_DOMAIN:-internal.test}

  minio:
    << : *default-opts
    image: ${SIMVA_MINIO_IMAGE:-quay.io/minio/minio}:${SIMVA_MINIO_VERSION:-RELEASE.2024-06-04T19-20-08Z}
    entrypoint: >
      /bin/sh -c '
        if [ ! -e "/etc/ssl/certs/internal-CA.pem" ]; then
          cp /root/.minio/certs/CAs/rootCA.pem "/etc/ssl/certs/internal-CA.pem";
          cat "/etc/ssl/certs/internal-CA.pem" >> /etc/ssl/cert.pem;
        fi;
        /usr/bin/docker-entrypoint.sh $$@;
      '
    command:
     - '--'
     - 'server'
     - '--console-address :9001'
     - '/data'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - minio_data:/data
# be advised if minio is launched as a non-root user you need to change this setting
# Note too that this setting it is only needed if using a non-recognized CA
# (https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html#install-certificates-from-third-party-cas)
      - ${SIMVA_TLS_HOME?TLS home folder required}/ca:/root/.minio/certs/CAs
      - ${SIMVA_CONTAINER_TOOLS_HOME:-/home/vagrant/docker-stacks/container-tools}:/container-tools
      - ${SIMVA_BIN_HOME:-/home/vagrant/simva-infra/docker-stacks/bin}/wait-available.sh:/bin/wait-available.sh:ro
    environment:
      MINIO_ROOT_USER: "${SIMVA_MINIO_ACCESS_KEY:-minio}"
      MINIO_BROWSER_REDIRECT_URL: "https://${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      MINIO_SERVER_URL: "https://${SIMVA_MINIO_API_HOST_SUBDOMAIN:-minio-api}.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      MINIO_ROOT_PASSWORD: "${SIMVA_MINIO_SECRET_KEY:-secret}"
      WAIT_TIMEOUT: ${SIMVA_WAIT_TIMEOUT:-240}
      SIMVA_WAIT_TIME: ${SIMVA_WAIT_TIME:-10}
      SIMVA_MAX_RETRIES: ${SIMVA_MAX_RETRIES:-20}
    restart: on-failure:${SIMVA_MAX_RETRIES:-20}
    healthcheck:
      test: "curl -sS http://localhost:9000/minio/health/live || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
    hostname: ${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - ${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - ${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.minio-ui-service.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio-ui.service=minio-ui-service"
      - "traefik.http.routers.minio-ui.rule=Host(`${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.services.minio-api-service.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-api.service=minio-api-service"
      - "traefik.http.routers.minio-api.rule=Host(`${SIMVA_MINIO_API_HOST_SUBDOMAIN:-minio-api}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"

volumes:
  minio_data:
    external: true
  minio_mig_data:
    external: true