version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  simva-api:
    build: ${SIMVA_API_GIT_REPO:-/home/vagrant/simva}
    restart: unless-stopped
    environment:
      LOG_LEVEL: "debug"
      JSTRACKER_LOCAL_DEPLOYMENT: "${SIMVA_JSTRACKER_LIBRARY_LOCAL_DEPLOYMENT}"
      JSTRACKER_LOCAL_PATH: "/home/node/js-tracker"
      JSTRACKER_ENTRYPOINT_SCRIPT: "/home/node/entrypoint.d/setup-local-deps.js"
    volumes:
      - ${SIMVA_API_GIT_REPO:-/home/vagrant/simva}:/home/node/app/
      - ${SIMVA_JSTRACKER_LIBRARY_LOCAL_PATH:-/home/vagrant/js-tracker}:/home/node/js-tracker
      - /home/node/js-tracker/node_modules  # Exclude node_modules
      - /home/node/app/node_modules  # Exclude node_modules
      - ${STACK_HOME?STACK home folder required}/etc/entrypoint.d/setup-local-deps.js:/home/node/entrypoint.d/setup-local-deps.js
    ports:
      - "127.0.0.1:9229:9229"
      - "127.0.0.1:9232:9230"
  simva-front:
    build: ${SIMVA_FRONT_GIT_REPO:-/home/vagrant/simva-front}
    restart: unless-stopped
    environment:
      LOG_LEVEL: "debug"
    volumes:
      - ${SIMVA_FRONT_GIT_REPO:-/home/vagrant/simva-front}:/home/node/app/
      - /home/node/app/node_modules  # Exclude node_modules
    ports:
      - "127.0.0.1:9230:9229"
      - "127.0.0.1:9233:9230"
  simva-trace-allocator:
    build: ${SIMVA_TRACE_ALLOCATOR_GIT_REPO:-/home/vagrant/simva-trace-allocator}
    restart: unless-stopped
    environment:
      LOG_LEVEL: "debug"
    volumes:
      - ${SIMVA_TRACE_ALLOCATOR_GIT_REPO:-/home/vagrant/simva-trace-allocator}:/home/node/app/
      - /home/node/app/node_modules  # Exclude node_modules
    ports:
      - "127.0.0.1:9231:9229"