version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    name: "${SIMVA_SERVICE_NETWORK:-traefik_services}"
    external: true
  
services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${SIMVA_LRS_DB_NAME:-lrs}
      POSTGRES_USER: ${SIMVA_LRS_DB_USER:-lrs}
      POSTGRES_PASSWORD: ${SIMVA_LRS_DB_PASSWORD:-lrs}
    networks:
        default:
          aliases:
            - db-lrs.${SIMVA_INTERNAL_DOMAIN:-internal.test}
        traefik_services:
          aliases:
            - db-lrs.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    volumes:
      - pgdata:/var/lib/postgresql
  lrs:
    image: yetanalytics/lrsql:latest
    command: ["/lrsql/bin/run_postgres.sh"]   # 🔥 IMPORTANT FIX
    restart: unless-stopped
    depends_on:
      - db
    environment:
      LRSQL_LOG_LEVEL: info
      LRSQL_DB_TYPE: postgres
      LRSQL_DB_HOST: db-lrs.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      LRSQL_DB_PORT: 5432
      LRSQL_DB_NAME: ${SIMVA_LRS_DB_NAME:-lrs}
      LRSQL_DB_USER: ${SIMVA_LRS_DB_USER:-lrs}
      LRSQL_DB_PASSWORD: ${SIMVA_LRS_DB_PASSWORD:-lrs}
      LRSQL_API_KEY_DEFAULT: ${SIMVA_LRS_API_KEY_DEFAULT:-my_api_key}
      LRSQL_API_SECRET_DEFAULT: ${SIMVA_LRS_API_SECRET_DEFAULT:-my_api_secret}
      LRSQL_ADMIN_USER_DEFAULT: ${SIMVA_LRS_ADMIN_USER_DEFAULT:-admin}
      LRSQL_ADMIN_PASS_DEFAULT: ${SIMVA_LRS_ADMIN_PASS_DEFAULT:-admin_password}
      LRSQL_SUPPORTED_VERSIONS: ${SIMVA_LRS_SUPPORTED_VERSIONS:-1.0.3,1.0.2,1.0.1,1.0.0}
      LRSQL_ALLOWED_ORIGINS: "https://${SIMVA_LRS_HOST_SUBDOMAIN:-lrs}.${SIMVA_EXTERNAL_DOMAIN:-external.test},https://${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      LRSQL_HTTP_HOST: 0.0.0.0
      LRSQL_HTTP_PORT: 8080
    networks:
      default:
        aliases:
          - ${SIMVA_LRS_HOST_SUBDOMAIN:-lrs}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - ${SIMVA_LRS_HOST_SUBDOMAIN:-lrs}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      traefik.enable: "true"
      traefik.http.services.lrs.loadbalancer.server.port: "8080"
      traefik.http.routers.lrs.rule: "Host(`${SIMVA_LRS_HOST_SUBDOMAIN:-lrs}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"

volumes:
  pgdata: