version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    name: "${SIMVA_SERVICE_NETWORK:-traefik_services}"
    external: true

services:
  mariadb:
    << : *default-opts
    image: ${SIMVA_MARIADB_IMAGE:-mariadb}:${SIMVA_MARIADB_VERSION:-10.4.13}
    volumes:
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/keycloak/mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${SIMVA_KEYCLOAK_MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${SIMVA_KEYCLOAK_MYSQL_DATABASE:-keycloak}
      - MYSQL_USER=${SIMVA_KEYCLOAK_MYSQL_USER:-keycloak}
      - MYSQL_PASSWORD=${SIMVA_KEYCLOAK_MYSQL_PASSWORD:-password}
# https://github.com/docker-library/mariadb/issues/261
# https://github.com/docker-library/mariadb/issues/262
      - MYSQL_INITDB_SKIP_TZINFO=true
    healthcheck:
      test: "mysqladmin ping -h localhost -u root -p${SIMVA_KEYCLOAK_MYSQL_ROOT_PASSWORD:-root} --silent"
      interval: 60s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    hostname: mariadb.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - mariadb.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}

  mariadb-backup:
    << : *default-opts
    image: ${SIMVA_MARIADB_IMAGE:-mariadb}:${SIMVA_MARIADB_VERSION:-10.4.13}
    volumes:
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/keycloak/mariadb-dump:/dump
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_CONTAINER_TOOLS_HOME:-/home/vagrant/docker-stacks/container-tools}:/container-tools
    environment:
      - MYSQL_HOST=mariadb.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      - MYSQL_ROOT_PASSWORD=${SIMVA_KEYCLOAK_MYSQL_ROOT_PASSWORD:-root}
      - BACKUP_NUM_KEEP=7
      - BACKUP_FREQUENCY=1d
      - WAIT_TIMEOUT=${SIMVA_WAIT_TIMEOUT:-240}
    entrypoint: |
      bash -c '/container-tools/wait-for-it.sh -h $${MYSQL_HOST} -p 3306 -t $${WAIT_TIMEOUT} -- bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        mysqldump --all-databases -h"$$MYSQL_HOST" -uroot -p"$$MYSQL_ROOT_PASSWORD" > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql
        (ls -t /dump/dump*.sql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    restart: unless-stopped
    hostname: mariadb-backup.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - mariadb.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}-backup.${SIMVA_INTERNAL_DOMAIN:-internal.test}

  mail:
    << : *default-opts
    image: maildev/maildev:1.1.0
    environment:
      - MAILDEV_SMTP_PORT=25
      - MAILDEV_WEB_PORT=80
    restart: unless-stopped
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://localhost:80/ || exit 1"
      interval: 60s
      timeout: 20s
      retries: 3
    hostname: ${SIMVA_MAIL_HOST_SUBDOMAIN:-mail}.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - "${SIMVA_MAIL_HOST_SUBDOMAIN:-mail}.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
