version: '3.7'

networks:
  traefik_services:
    external: true

services:

  whoami:
    image: containous/whoami
    volumes:
      - /etc/localtime:/etc/localtime:ro
    hostname: whoami.keycloak.internal.test
    networks:
      default:
        aliases:
          - "whoami.keycloak.internal.test"
      traefik_services:
        aliases:
          - "whoami.keycloak.internal.test"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN_SUFFIX:-external.test}`)"

  simplesamlphp:
    image: eucm/simplesamlphp:1.18.7
    environment:
      DEBUG: "true"
      SIMPLESAMLPHP_PATH: "/simplesamlphp"
      SIMPLESAMLPHP_ADMIN_PASSWORD: "admin"
      SIMPLESAMLPHP_LOG_LEVEL: "DEBUG"
      SIMPLESAMLPHP_ENABLE_DEFAULT_VHOST: "true"
      SIMPLESAMLPHP_INTERNAL_PROXY_HOSTNAME: "traefik.internal.test"
      MSMTP_HOST: "mail.internal.test"
      MSMTP_FROM: "no-reply@simplesamlphp.external.test"
      SIMPLESAMLPHP_ADMIN_PROTECT_INDEX_PAGE: "true"
      SIMPLESAMLPHP_SP_CERT_SUBJ: "/C=ES/ST=Madrid/L=Madrid/O=Universidad Complutense de Madrid/OU=e-UCM SIMVA/CN=simplesamlphp.internal.test"
      SIMPLESAMLPHP_SP_IDP_METADATA_URL: "https://sso.external.test/realms/simva/protocol/saml/descriptor"
      SIMPLESAMLPHP_SIGN_AUTHN_REQUESTS: "true"
      SIMPLESAMLPHP_SIGN_LOGOUT_REQUESTS: "true"
    hostname: simplesamlphp.keycloak.internal.test
    networks:
      default:
        aliases:
          - "simplesamlphp.keycloak.internal.test"
      traefik_services:
        aliases:
          - "simplesamlphp.keycloak.internal.test"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.simplesamlphp.loadbalancer.server.port=80"
      - "traefik.http.routers.simplesamlphp.rule=Host(`simplesamlphp.${DOMAIN_SUFFIX:-external.test}`)"
