version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    external: true

services:
  schema-registry-ui:
    << : *default-opts
#    image: landoop/schema-registry-ui:0.9.5
    image: landoop/schema-registry-ui:latest
    environment:
      SCHEMAREGISTRY_URL: http://schema-registry.${SIMVA_INTERNAL_DOMAIN:-internal.test}:8085/
      PROXY: "true"
# XXX: See https://github.com/stefanprodan/dockprom/issues/205
# sol: https://github.com/stefanprodan/dockprom/issues/205#issuecomment-798628548
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_CONFIG_HOME:-/home/vagrant/docker-stacks/config}/kafka/schema-registry-ui/resolv.conf:/etc/resolv.conf:ro
    depends_on:
      - schema-registry
    hostname: schema-registry-ui.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - schema-registry-ui.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - schema-registry-ui.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.schema-registry-ui.loadbalancer.server.port=8000"
      - "traefik.http.routers.schema-registry-ui.rule=Host(`schema-registry-ui.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
