version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  kafka-rest-proxy:
    << : *default-opts
    image: confluentinc/cp-kafka-rest:${SIMVA_KAFKA_VERSION:-5.5.0}
    environment:
      KAFKA_REST_LISTENERS: http://0.0.0.0:8086/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry.${SIMVA_INTERNAL_DOMAIN:-internal.test}:8085/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1.${SIMVA_INTERNAL_DOMAIN:-internal.test}:19092
    depends_on:
      - zk1
      - kafka1
      - schema-registry
    volumes:
      - /etc/localtime:/etc/localtime:ro
    hostname: kafka-rest-proxy.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - kafka-rest-proxy.${SIMVA_INTERNAL_DOMAIN:-internal.test}