version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    external: true

services:
  topics-ui:
    << : *default-opts
#    image: landoop/kafka-topics-ui:0.9.4
    image: landoop/kafka-topics-ui:latest
    environment:
      KAFKA_REST_PROXY_URL: http://kafka-rest-proxy.${SIMVA_INTERNAL_DOMAIN:-internal.test}:8086/
      PROXY: "true"
# XXX: See https://github.com/stefanprodan/dockprom/issues/205
# sol: https://github.com/stefanprodan/dockprom/issues/205#issuecomment-798628548
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - kafka-rest-proxy
    hostname: topics-ui.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - topics-ui.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - topics-ui.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.topics-ui.loadbalancer.server.port=8000"
      - "traefik.http.routers.topics-ui.rule=Host(`topics-ui.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"

  zoonavigator:
    << : *default-opts
    restart: unless-stopped
    image: elkozmon/zoonavigator:1.0.1
    environment:
      HTTP_PORT: 9000
      CONNECTION_ZK1_NAME: zk1.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      CONNECTION_ZK1_CONN: zk1.${SIMVA_INTERNAL_DOMAIN:-internal.test}:2181
      AUTO_CONNECT_CONNECTION_ID: ZK1
    depends_on:
      - zk1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    hostname: zoonavigator.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - zoonavigator.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - zoonavigator.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.zoonavigator.loadbalancer.server.port=9000"
      - "traefik.http.routers.zoonavigator.rule=Host(`zoonavigator.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
