version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    external: true

services:
  kafka-ui:
    image: ${SIMVA_KAKFA_UI_IMAGE:-provectuslabs/kafka-ui}:${SIMVA_KAKFA_UI_VERSION:-latest}
    environment:
      KAFKA_CLUSTERS_0_NAME: SIMVA
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1.${SIMVA_INTERNAL_DOMAIN:-internal.test}:9092
      #KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry.${SIMVA_INTERNAL_DOMAIN:-internal.test}:8085/
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: Kafka Connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect.${SIMVA_INTERNAL_DOMAIN:-internal.test}:8083/
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - kafka-rest-proxy
      - connect
      - schema-registry
      - kafka1
    networks:
      default:
        aliases:
          - ${SIMVA_KAFKA_UI_HOST_SUBDOMAIN:-kafka-ui}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - ${SIMVA_KAFKA_UI_HOST_SUBDOMAIN:-kafka-ui}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.kafka-ui.loadbalancer.server.port=8080"
      - "traefik.http.routers.kafka-ui.rule=Host(`${SIMVA_KAFKA_UI_HOST_SUBDOMAIN:-kafka-ui}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.kafka-ui.middlewares=dashboardAuth@file"

  zoonavigator:
    << : *default-opts
    restart: unless-stopped
    image: elkozmon/zoonavigator:1.0.1
    environment:
      HTTP_PORT: 9000
      CONNECTION_ZK1_NAME: zk1.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      CONNECTION_ZK1_CONN: zk1.${SIMVA_INTERNAL_DOMAIN:-internal.test}:2181
      AUTO_CONNECT_CONNECTION_ID: ZK1
    depends_on:
      - zk1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    hostname: ${SIMVA_ZOONAVIGATOR_HOST_SUBDOMAIN:-zoonavigator}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - ${SIMVA_ZOONAVIGATOR_HOST_SUBDOMAIN:-zoonavigator}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - ${SIMVA_ZOONAVIGATOR_HOST_SUBDOMAIN:-zoonavigator}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.zoonavigator.loadbalancer.server.port=9000"
      - "traefik.http.routers.zoonavigator.rule=Host(`${SIMVA_ZOONAVIGATOR_HOST_SUBDOMAIN:-zoonavigator}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.zoonavigator.middlewares=dashboardAuth@file"