[global]
    checkNewVersion = false
    sendAnonymousUsage = false

[ping]
    entryPoint = "ping"

[api]
    dashboard = true

[providers]
    [providers.file]
        directory = "/etc/traefik/dynamic-config"
        watch = true

    [providers.docker]
        exposedByDefault = false
        watch = true
        endpoint = "tcp://socket-proxy.{{ .Env.SIMVA_INTERNAL_DOMAIN }}:2375"
        network = "{{ .Env.SIMVA_SERVICE_NETWORK }}"
        defaultRule = "Host(`{{ "{{" }} .Name {{ "}}" }}.{{.Env.SIMVA_EXTERNAL_DOMAIN }}`)"

[entryPoints]
    [entryPoints.ping]
        address = ":8082"

    [entryPoints.web]
        address = ":80"
        [entryPoints.web.forwardedHeaders]
            trustedIPs = [ "{{ .Env.SIMVA_LOAD_BALANCER_IPS }}" ]
    [entryPoints.websecure]
        address = ":443"
        [entryPoints.websecure.http.tls]

[serversTransport]
    insecureSkipVerify = {{ .Env.SIMVA_TRAEFIK_INSECURE_SKIP_VERIFY }}
    rootcas = [ "{{ .Env.SIMVA_SSL_ROOT_CAS }}" ]

[log]
    level = "{{ .Env.SIMVA_TRAEFIK_LOG_LEVEL }}"
    format = "json"

[accesslog]
    format = "json"
