version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  default:
    name: "simva-local_dev"
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "sdev0"
    ipam:
      driver: default
      config:
        - subnet: "172.29.0.0/24"

services:
  dns-proxy-server:
    << : *default-opts
    image: eucm/dns-proxy-server:2.19.0-dh-2
    entrypoint:
      - '/bin/sh'
      - '-c'
      - |
        [ ! -d "/app/conf" ] && mkdir -p /app/conf;
        [ ! -f "/app/conf/config.json" ] && cat << EOF > /app/conf/config.json
        {
          "version": 2,
          "remoteDnsServers": [
            "8.8.8.8:53",
            "8.8.4.4:53"
          ],
          "envs": [
            {
              "name": "",
              "hostnames": [
                {
                  "id": 1562843575352085033,
                  "hostname": ".external.test",
                  "ip": "172.29.0.1",
                  "ttl": 3600,
                  "type": "A"
                },
                {
                  "id": 1562843575352085034,
                  "hostname": ".dev.test",
                  "ip": "172.29.0.1",
                  "ttl": 3600,
                  "type": "A"
                }
              ]
            }
          ],
          "activeEnv": "",
          "webServerPort": 5380,
          "dnsServerPort": 53,
          "defaultDns": false,
          "logLevel": "INFO",
          "logFile": "console",
          "dpsNetwork": false,
          "dpsNetworkAutoConnect": false,
          "registerContainerNames": true,
          "hostMachineHostname": "host.docker.test",
          "domain": "docker.test"
        }
        EOF
        exec /usr/bin/docker-entrypoint "$$@"
    command:
      - "--"
      - "/app/dns-proxy-server"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      MG_LOG_LEVEL: "DEBUG"
    hostname: "dns.dev.test"
    networks:
      default:
        ipv4_address: "172.29.0.53"
        aliases:
          - "dns.dev.test"

#
#
#
  mongodb:
    << : *default-opts
    image: ${SIMVA_MONGODB_IMAGE:-mongo}:${SIMVA_MONGODB_VERSION:-4.2.8}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/simva/mongo:/data/db
    hostname: ${SIMVA_MONGO_HOST_SUBDOMAIN:-simva-mongo}.dev.test
    networks:
      default:
        aliases:
          - ${SIMVA_MONGO_HOST_SUBDOMAIN:-simva-mongo}.dev.test

  simva-api:
    << : *default-opts
    image: ${SIMVA_SIMVA_IMAGE:-node}:${SIMVA_SIMVA_FRONT_VERSION:-12.18.2}
    command: bash -c "cd /app && chmod +x docker-startup.sh && ./docker-startup.sh"
    stdin_open: true
    tty: true
    environment:
      DEBUG: "true"
      NODE_ENV: "development"
      EXTERNAL_URL: http://localhost:3000
      MONGO_HOST: ${SIMVA_MONGO_HOST_SUBDOMAIN:-simva-mongo}.dev.test
      MONGO_DB: /simva
      KAFKA_HOST: kafka1.dev.test
      KAFKA_PORT: 9092
      KAFKA_TOPIC: ${SIMVA_TRACES_TOPIC:-traces}
      MINIO_URL: https://${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}.${SIMVA_EXTERNAL_DOMAIN:-external.test}/
      MINIO_BUCKET: ${SIMVA_TRACES_BUCKET_NAME:-traces}
      LIMESURVEY_PROTOCOL: https
      LIMESURVEY_HOST: ${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_EXTERNAL_DOMAIN:-external.test}
      LIMESURVEY_PORT: 443
      LIMESURVEY_EXTERNAL: https://${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_EXTERNAL_DOMAIN:-external.test}/
      LIMESURVEY_ADMIN_USER: ${SIMVA_LIMESURVEY_ADMIN_USER:-admin}
      LIMESURVEY_ADMIN_PASSWORD: ${SIMVA_LIMESURVEY_ADMIN_PASSWORD:-secret}
      A2_HOST: "${SIMVA_A2_HOST:-a2}"
      A2_PORT: "3000"
      A2_PROTOCOL: "http"
      A2_ADMIN_USER: "${SIMVA_A2_ADMIN_USER:-root}"
      A2_ADMIN_PASSWORD: "${SIMVA_A2_ADMIN_PASSWORD:-password}"
      A2_EXTERNAL: "https://${SIMVA_ANALYTICS_HOST_SUBDOMAIN:-analytics}.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      NODE_EXTRA_CA_CERTS: /var/lib/simva/ca/rootCA.pem
      SSO_ENABLED: "true"
      SSO_HOST: ${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_EXTERNAL_DOMAIN:-external.test}
      SSO_ADMIN_USER: ${SIMVA_ADMINISTRATOR_USER:-administrator}
      SSO_ADMIN_PASSWORD: ${SIMVA_ADMINISTRATOR_PASSWORD:-administrator}
    volumes:
      - ${SIMVA_TLS_HOME?TLS home folder required}/ca:/var/lib/simva/ca
#      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/simva/simva-api:/app
# XXX For development
      - /home/casa/ivan/keycloak-nodejs/simva:/app

    depends_on:
      - mongodb
    hostname: ${SIMVA_SIMVA_API_HOST_SUBDOMAIN:-simva-api}dev.test
    networks:
      default:
        aliases:
          - ${SIMVA_SIMVA_API_HOST_SUBDOMAIN:-simva-api}dev.test
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
      - target: 9229
        published: 9230
        protocol: tcp
        mode: host

  simva-front:
    << : *default-opts
    image: ${SIMVA_SIMVA_IMAGE:-node}:${SIMVA_SIMVA_FRONT_VERSION:-12.18.2}
    command: bash -c "cd /app && chmod +x docker-startup.sh && ./docker-startup.sh"
    stdin_open: true
    tty: true
    environment:
      DEBUG: "true"
      NODE_ENV: "development"
      SIMVA_PORT: "3050"
      SIMVA_HOST: "localhost"
      SIMVA_PROTOCOL: "http"
      NODE_EXTRA_CA_CERTS: /var/lib/simva/ca/rootCA.pem
      MONGO_DB: /simva
      SIMVA_API_HOST: ${SIMVA_SIMVA_API_HOST_SUBDOMAIN:-simva-api}dev.test
      SIMVA_API_PORT: "3000"
      SIMVA_API_PROTOCOL: "http"
      SSO_HOST: ${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_EXTERNAL_DOMAIN:-external.test}
      SSO_CLIENT_ID: "${SIMVA_SIMVA_CLIENT_ID:-simva}"
      SSO_CLIENT_SECRET: "${SIMVA_SIMVA_CLIENT_SECRET:-secret}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_TLS_HOME?TLS home folder required}/ca:/var/lib/simva/ca
#      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/simva/simva-front:/app
# XXX For development
      - /home/casa/ivan/keycloak-nodejs/simva-front:/app
    depends_on:
      - simva-api
    hostname: simva-front.dev.test
    networks:
      default:
        aliases:
          - simva-front.dev.test
    ports:
      - target: 3050
        published: 3050
        protocol: tcp
        mode: host
      - target: 9229
        published: 9229
        protocol: tcp
        mode: host
