version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  mongodb:
    << : *default-opts
    image: mongo:4.2.8
    networks:
      traefik_services:
        aliases:
          - ${SIMVA_MONGO_HOST_SUBDOMAIN:-simva-mongo}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.simva-mongodb.loadbalancer.server.port=27017"
      - "traefik.tcp.routers.simva-mongodb.rule=HostSNI(`${SIMVA_MONGO_HOST_SUBDOMAIN:-simva-mongo}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
